# Generated by Django 2.2.6 on 2019-10-13 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TinyURL',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('original', models.TextField(blank=True)),
                ('short', models.CharField(blank=True, max_length=255)),
                ('alias', models.CharField(blank=True, max_length=255)),
                ('clicks', models.IntegerField(default=0)),
                ('time', models.DurationField()),
            ],
        ),
    ]
