# Generated by Django 2.2.6 on 2019-10-13 20:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tinyurl',
            name='original',
            field=models.TextField(),
        ),
    ]
