# Generated by Django 2.2.6 on 2019-10-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0002_auto_20191013_2045'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinyurl',
            name='short',
        ),
        migrations.AlterField(
            model_name='tinyurl',
            name='original',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
