# Generated by Django 2.2.6 on 2019-10-16 13:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tiny', '0003_auto_20191013_2052'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tinyurl',
            name='time',
        ),
    ]
